version: '2'

networks:
  default:
    ipam:
      config:
        - subnet: 172.32.0.0/16
          ip_range: 172.32.0.0/16
          gateway: 172.32.0.1
  rng:
  hasher:

services: 
  rng:
    image: guismo/rng
    labels:
      loadbalancer: rng-lb
    networks:  
      rng:
        aliases:
          - rng-be
    environment:
      DEBUG: 'yes'
  rng-lb:  
    command: 80 rng-be 80
    depends_on: 
      - rng
    image: jpetazzo/hamba
    networks:
      default:
        aliases:
          - rng
      rng:
    environment:
      DEBUG: 'yes'

  hasher:
    image: guismo/hasher
    labels:
      loadbalancer: hasher-lb
    networks:  
      hasher:
       aliases:
         - hasher-be
    environment:
      DEBUG: 'yes'
  hasher-lb:  
    command: 80 hasher-be 80
    depends_on: 
      - hasher
    image: jpetazzo/hamba
    networks:
      default:
        aliases:
          - hasher
      hasher:
    environment:
      DEBUG: 'yes'

  webui:
    image: guismo/webui
    ports:
      - 80
    environment:
      DEBUG: 'yes'

  redis:
    image: redis

  worker:
    image: guismo/worker
    environment:
      DEBUG: 'yes'
